#
# Target's name
#
TARGET=xmprog

#
# Object files
#
OBJS=main.o uart.o ctimer.o xmprog.o addr_port.o data_port.o flash_hw.o flash_ops.o ctrl_pins.o chips.o eeprom_hw.o eeprom_ops.o

include ../common/Makefile.mk
