#!/usr/bin/python3

class Serial:
    def __init__(self, port: str, baudrate: int, timeout: float) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def write(self, data: bytes) -> None: ...
    def readline(self) -> bytes: ...
