#!/usr/bin/python3

from typing import Iterable, Optional
from gi.repository import Gtk
from gi.repository import GdkPixbuf
from gi.repository import Gdk

class View(Gtk.TextView):
    def set_show_line_numbers(self, show: bool) -> None: ...
    def set_show_line_marks(self, show: bool) -> None: ...
    def set_highlight_current_line(self, highlight: bool) -> None: ...
    def set_mark_attributes(self, category: str, attributes: MarkAttributes, priority: int) -> None: ...
    def get_buffer(self) -> Buffer: ...

class MarkAttributes:
    def set_pixbuf(self, pixbuf: GdkPixbuf.Pixbuf) -> None: ...
    def set_background(self, background: Gdk.RGBA) -> None: ...

class Mark(Gtk.TextMark): ...

class Buffer(Gtk.TextBuffer):
    def set_text(self, text: str) -> None: ...
    def get_source_marks_at_iter(self, iter: Gtk.TextIter, category: str) -> Iterable[Mark]: ...
    def remove_source_marks(self, start: Gtk.TextIter, end: Gtk.TextIter, category: str) -> None: ...
    def create_source_mark(self, name: Optional[str], category: str, where: Gtk.TextIter) -> Mark: ...
