GP_REG_SRC=../cpu-modules/gp_register.v ../chips/dff_377.v ../chips/dff_374.v ../chips/buffer_245.v
CONST_ARG_SRC=../cpu-modules/const_arg.v ../chips/buffer_245.v
ALU_ADD_SUB_SRC=../cpu-modules/alu_addsub.v ../chips/buffer_245.v ../chips/adder_283.v ../chips/xor_86b.v ../chips/xor_86p.v ../chips/and_08p.v ../chips/buffer_125p.v
ALU_AND_SRC=../cpu-modules/alu_and.v ../chips/buffer_245.v ../chips/and_08b.v
ALU_OR_SRC=../cpu-modules/alu_or.v ../chips/buffer_245.v ../chips/or_32b.v
ALU_XOR_SRC=../cpu-modules/alu_xor.v ../chips/buffer_245.v ../chips/xor_86b.v ../chips/or_32b.v
ALU_SHIFT_SRC=../cpu-modules/alu_shift.v ../chips/buffer_245.v ../chips/buffer_125p.v
ALU_SWAP_SRC=../cpu-modules/alu_swap.v ../chips/buffer_245.v
FLG_REG_SRC=../cpu-modules/flags_reg.v ../chips/dff_173.v ../chips/nor_02b.v ../chips/and_08p.v ../chips/mux_157b.v ../chips/buffer_125p.v
ADDRESS_COUNTER_SRC=../cpu-modules/address_counter.v ../chips/dff_374.v ../chips/udcounter_193.v ../chips/or_32p.v ../chips/nand_00p.v
MEMORY_SRC=../cpu-modules/memory.v ../chips/ram_62256.v ../chips/nand_00p.v ../chips/nand_10p.v ../chips/buffer_245.v ../chips/rom_async.v
I_REG_SRC=../cpu-modules/i_register.v ../chips/dff_173.v
TX_REG_SRC=../cpu-modules/tx_register.v ../chips/dff_377.v ../chips/mux_157b.v ../chips/buffer_245.v ../chips/and_08p.v
ADDRESS_CALC_SRC=../cpu-modules/address_calc.v ../chips/dff_377.v ../chips/adder_283.v ../chips/buffer_245.v ../chips/and_08p.v
IO_CTRL_SRC=../cpu-modules/io_control.v ../chips/dff_377.v ../chips/demux_138.v ../chips/buffer_245.v
CONTROL_SRC=../cpu-modules/control_logic.v ../chips/counter_161.v ../chips/dff_74.v ../chips/nand_00p.v ../chips/rom_async.v
CLOCK_SRC=../cpu-modules/clock.v ../chips/dff_74.v ../chips/nand_00p.v ../chips/nor_02p.v ../chips/xor_86p.v
DEMUX_16_SRC=../cpu-modules/demux_16.v ../chips/demux_138.v
ALU_BLOCK_SRC=../cpu-modules/alu_block.v $(GP_REG_SRC) $(CONST_ARG_SRC) $(ALU_ADD_SUB_SRC) $(ALU_AND_SRC) $(ALU_OR_SRC) $(ALU_XOR_SRC) $(ALU_SHIFT_SRC) $(ALU_SWAP_SRC) $(FLG_REG_SRC) $(DEMUX_16_SRC) ../chips/demux_138.v
MEMORY_BLOCK_SRC=../cpu-modules/mem_block.v $(MEMORY_SRC) $(I_REG_SRC) $(TX_REG_SRC) $(ADDRESS_COUNTER_SRC) $(ADDRESS_CALC_SRC) $(DEMUX_16_SRC) ../chips/demux_138.v
IO_BLOCK_SRC=../cpu-modules/io_block.v $(IO_CTRL_SRC) $(DEMUX_16_SRC) ../chips/demux_138.v ../cpu-modules/display_num.v ../cpu-modules/display_char.v ../cpu-modules/display_lcd.v ../cpu-modules/uart.v
CPU_SRC=../cpu-modules/cpu.v ../cpu-modules/debug.v ../cpu-modules/clock_simple.v ../cpu-modules/cword_splitter.v $(ALU_BLOCK_SRC) $(MEMORY_BLOCK_SRC) $(CONTROL_SRC) $(IO_BLOCK_SRC)
