#!/usr/bin/python3

def print_digitMap_member(formattedNum):

    members=[]
    for chr in formattedNum:
        if (chr == " "):
            members.append("DIGIT_BLANK")
        elif (chr == "-"):
            members.append("DIGIT_MINUS")
        else:
            members.append("DIGIT_{}".format(chr))

    line = "        /* {} */ {{ ".format(formattedNum) + ", ".join(reversed(members)) + "},"

    print (line)


print ("const uint8_t digitMap[][256][NUM_DISPLAYS] PROGMEM = {")
print ("    /* The contents were generated by Python script */")

print ("    {")
for a in range(256):
    print_digitMap_member ("{:4}".format(a))
print ("    },")

print ("    {")
for a in range (128):
    print_digitMap_member ("{:4}".format(a))
for a in range (-128, 0):
    print_digitMap_member ("{:4}".format(a))
print ("    },")

print ("    {")
for a in range (256):
    print_digitMap_member ("{:4X}".format(a))
print ("    },")

print ("    {")
for a in range (256):
    print_digitMap_member ("{:4o}".format(a))
print ("    },")

print ("};")