# This workflow will install Python dependencies, check type annotations and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyControl checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install tools and libraries
      run: |
        sudo add-apt-repository -y ppa:velko/compilers
        sudo apt-get install -y socat iverilog customasm
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pytest pyserial
    - name: Install localpath helper
      working-directory: ./pycontrol
      run: |
        pip install ./localpath-0.1
    - name: Generate control ROMs
      working-directory: ./pycontrol/tools
      run: |
        python microcode.py
    - name: Compile BIOS ROM
      working-directory: ./bios
      run: |
        make
    - name: Hardware emulator - Verilog testbenches
      working-directory: ./emulator/tests
      run: |
        make test
    - name: Build and start hardware emulator
      working-directory: ./emulator/vm
      run: |
        make
        socat PTY,link=/tmp/cpu8pty0,raw,echo=0 PTY,link=/tmp/cpu8pty1,raw,echo=0 &
        sleep 0.5
        make run &
    - name: Check typing with MyPy
      working-directory: ./pycontrol
      env:
        MYPYPATH: stubs
      run: |
        python -m mypy --strict libcpu tests tools ../tools
    - name: Run tests
      working-directory: ./pycontrol
      run: |
        python -m pytest
    - name: Run demo programs
      working-directory: ./demo
      run: |
        customasm hello.asm
        python ../tools/exec_bin.py hello.bin | grep -q "Hello, World!"
        customasm prime_sieve.asm
        python ../tools/exec_bin.py prime_sieve.bin | diff -u primes.txt -
        customasm double_dabble.asm
        python ../tools/exec_bin.py double_dabble.bin | grep -q "36324058"
        customasm uart_output.asm
        python ../tools/exec_bin.py -M uart_output.bin | diff -u uart_output.txt -
